### PR TITLE
refactor: add ujson support

### PR DESCRIPTION
**Pull request by QuartzWarrior**
## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes. (None needed, did change README though)
  - [x] I have run `task pyright` and fixed the relevant issues. (None of the issues related to my new code)
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by ooliver1 — COMMENTED** [review]
This is missing the entire dependency. I would recommend implementation locks on those if this is only because orjson is CPython reliant:
```py
# setup.py#52
    "speed": [
        "orjson>=3.5.4; python_implementation == 'CPython'",
        "ujson>=5.7.0; python_implementation != 'CPython'",
        "aiohttp[speedups]",
    ],
```

```sh
# PyPy output:
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 charset-normalizer-3.1.0 frozenlist-1.3.3 multidict-6.0.4 nextcord-2.5.0a4228+g8a04ed3b typing-extensions-4.5.0 ujson-5.7.0 yarl-1.8.2
```
```sh
# CPython output:
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 charset-normalizer-3.1.0 frozenlist-1.3.3 idna-3.4 multidict-6.0.4 nextcord-2.5.0a4228+g8a04ed3b orjson-3.8.9 typing-extensions-4.5.0 yarl-1.8.2
```

I am unsure about if the `aiohttp[speedups]` requirement may need to be changed since PyPy 3.8 cannot build `cChardet`.

**Comment by QuartzWarrior** [comment]
> This is missing the entire dependency. I would recommend implementation locks on those if this is only because orjson is CPython reliant:
> 
> ```python
> # setup.py#52
>     "speed": [
>         "orjson>=3.5.4; python_implementation == 'CPython'",
>         "ujson>=5.7.0; python_implementation != 'CPython'",
>         "aiohttp[speedups]",
>     ],
> ```
> 
> ```shell
> # PyPy output:
> Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 charset-normalizer-3.1.0 frozenlist-1.3.3 multidict-6.0.4 nextcord-2.5.0a4228+g8a04ed3b typing-extensions-4.5.0 ujson-5.7.0 yarl-1.8.2
> ```
> 
> ```shell
> # CPython output:
> Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 charset-normalizer-3.1.0 frozenlist-1.3.3 idna-3.4 multidict-6.0.4 nextcord-2.5.0a4228+g8a04ed3b orjson-3.8.9 typing-extensions-4.5.0 yarl-1.8.2
> ```
> 
> I am unsure about if the `aiohttp[speedups]` requirement may need to be changed since PyPy 3.8 cannot build `cChardet`.

I didn't add the dependency to it as it is optional, but that is a way to add it, thanks. Also, PyPy 3.9 can build `cChardet` fine.

**Review by Skelmis — COMMENTED** [review]
Please resolve lint actions, this may just be a case of adding the deps to build actions

**Comment by Skelmis** [comment]
> > Please resolve lint actions, this may just be a case of adding the deps to build actions
> 
> I've been looking for where I can change this, but I can't find anything. The closest I found is .github/workflows/lint.yml, but I'm not sure exactly where.

Take a look at `requirements-dev.txt`

**Comment by QuartzWarrior** [comment]
> Take a look at `requirements-dev.txt`

I'm sorry, but the only things I see in `requirements-dev.txt` don't seem to have anything to do with the actual nextcord module. Do you just want me to add ujson to it?

**Comment by Skelmis** [comment]
> 

They are installed during workflow runs

**Comment by ooliver1** [comment]
I do not think adding a third json implementation is the best solution. An interface to provide your own decoders would be a better solution, over adding yet another optional dependency very few people need.

**Pull request closed without merging**
