### PR TITLE
Remove **kwargs where applicable

### PR DESCRIPTION
**Pull request by Skelmis**
## Summary

Discord.py had a prolific use of **kwargs where it is unnecessary. This makes it both hard for new developers and experienced developers alike to get arguments right in what should be as simple as your editor pointing out the arguments.

This PR removes **kwargs where applicable while maintaining the same usage. 

Note, this will break people being dumb and passing key word arguments that things don't take. Although I could keep that functionality although quite frankly I think its not a good idea.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Skelmis** [comment]
If this is something you are against (and I don't see why you'd be against making it easier to use), please let me know asap so I don't waste my time improving the library.

**Comment by RPSMain** [comment]
is it just me or was the code linted? 🤔

**Comment by ooliver1** [comment]
@Skelmis could you redo it without auto formatting

**Comment by ooliver1** [comment]
However personally I would say it's a good idea, I've had many times I'd have to open a browser just to see valid kwargs

**Comment by rf20008** [comment]
This is going to be a breaking change (so we should keep **kwargs but not use it). 
However, LGTM to me so far (assuming this is tested)

**Comment by Skelmis** [comment]
Stalling this over the holidays then will see where everything stands down the line.

**Comment by TAG-Epic** [comment]
> This is going to be a breaking change (so we should keep **kwargs but not use it). 

Honestly not a fan of it

**Comment by ooliver1** [comment]
^, like why is the user still using old kwargs, it should tell them its not needed anymore/doesnt exist

**Comment by Skelmis** [comment]
I no longer have the motivation to do this. 

Might re-open in the future but as it currently stands I don't think I'll be getting back to that point any time soon.

**Pull request closed without merging**
