### PR TITLE
fix: menu assigning failing due to read only attributes

### LINKED ISSUE #1103: Regression in StringSelect types
### Summary

Master branch has a StringSelect regression where subclassing now break with the error seen below

### Reproduction Steps

Use the following code with the master branch. https://paste.disnake.dev/?id=1690608278173887

### Minimal Reproducible Code

_No response_

### Expected Results

Select works as expected

### Actual Results

```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/client.py", line 497, in _run_event
    await coro(*args, **kwargs)
  File "/home/skelmis/Code/test_ creds/main.py", line 43, in on_ready
    bot.add_view(MyView(bot))
  File "/home/skelmis/Code/test_ creds/main.py", line 13, in __init__
    self.add_item(MySelect())
  File "/home/skelmis/Code/test_ creds/main.py", line 31, in __init__
    super().__init__(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/ui/select/string.py", line 86, in __init__
    super().__init__(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/ui/select/base.py", line 123, in __init__
    self._underlying = SelectMenu._raw_construct(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/components.py", line 85, in _raw_construct
    setattr(self, slot, value)
AttributeError: 'StringSelectMenu' object attribute 'type' is read-only

```

### Intents

N/A

### System Information

Master branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Initially reported [here](1133141064639860837)

### PR DESCRIPTION
**Pull request by Skelmis**
## Summary

Types are now hard coded onto menus and are also read only, this resolves an issue where the underlying constructor would try to override that attribute resulting in an error

Closes #1103 

<!--
## This is a **Code Change**

- [X] I have tested my changes.
- [ ] I have updated the documentation to reflect the changes.
- [X] I have run `task pyright` and fixed the relevant issues.

### CODE REVIEW

**Review by Gangsta-Muffin — APPROVED** [review]
Fixes the issue for my code aswell 👍

**Review by ooliver1 — COMMENTED** [review]
I believe that class attributes don't even need to be in `__slots__` at all anyway.

**Review by Mac0501 — APPROVED** [review]
Tested every component the changes work for me.

**Comment by ooliver1** [comment]
> I believe that class attributes don't even need to be in `__slots__` at all anyway.

```patch
From a4a80c117a067573cd905f3a66921d77d790faa6 Mon Sep 17 00:00:00 2001
From: Oliver Wilkes <oliverwilkes2006@icloud.com>
Date: Tue, 8 Aug 2023 15:33:55 +0100
Subject: [PATCH] refactor(components): remove type from __slots__

---
 nextcord/components.py | 6 +-----
 1 file changed, 1 insertion(+), 5 deletions(-)

diff --git a/nextcord/components.py b/nextcord/components.py
index c26939be..342e48c2 100644
--- a/nextcord/components.py
+++ b/nextcord/components.py
@@ -64,7 +64,7 @@ class Component:
         The type of component.
     """
 
-    __slots__: Tuple[str, ...] = ("type",)
+    __slots__: Tuple[str, ...] = ()
 
     __repr_info__: ClassVar[Tuple[str, ...]]
     type: ComponentType
@@ -77,10 +77,6 @@ class Component:
     def _raw_construct(cls, **kwargs) -> Self:
         self = cls.__new__(cls)
         for slot in get_slots(cls):
-            if slot == "type" and getattr(self, slot, None) is not None:
-                # nextcord/issues/1103
-                continue
-
             try:
                 value = kwargs[slot]
             except KeyError:
-- 
2.39.2
```
> A declaration inside a class that saves memory by pre-declaring space for instance attributes and eliminating instance dictionaries.
<https://docs.python.org/3/glossary.html#term-__slots__>
so `__slots__` is only for instance attributes

**Review by m2ksims — APPROVED** [review]

**Pull request merged**
