### PR TITLE
Feat: Healthcheck

### PR DESCRIPTION
**Pull request by TAG-Epic**
## Summary
This checks that everything in the library is as it should

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by ooliver1 — APPROVED** [review]
assuming you've tested, LGTM

**Review by rf20008 — APPROVED** [review]
LGTM assuming you've tested the changes :)

**Review by vcokltfre — CHANGES_REQUESTED** [review]
health_check.py is definitely not PEP8 compliant, I'd suggest trying to keep new modules PEP8 compliant to make contributing easier and more consistent.

**Comment by rf20008** [comment]
@TAG-Epic you need to catch pkg_resources.DistributionNotFound instead of all exceptions because warnings are technically built-in exceptions. Also you might want to warn with something other than a UserWarning which is the default warning if you don't specify a different warning in the category parameter in warnings.warn()

otherwise LGTM

**Review by rf20008 — APPROVED** [review]
LGTM. One thing you should consider is a different type of warning :)

**Review by rf20008 — APPROVED** [review]
LGTM

**Pull request merged**
