### PR TITLE
Added member example

### PR DESCRIPTION
**Pull request by techpluscraft**
## Summary

This adds a member select example to application_command examples.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by VincentRPS** [comment]
Already done iirc in the docs pull aswell

**Comment by techpluscraft** [comment]
> Already done iirc in the docs pull aswell

Is it in the examples file?

**Comment by VincentRPS** [comment]
> > Already done iirc in the docs pull aswell
> 
> Is it in the examples file?

Wdym?

**Comment by VincentRPS** [comment]
There is a example completely like this made in the docs pull

**Pull request closed without merging**
