### PR TITLE
Refactor migrating docs to make them clearer.

### PR DESCRIPTION
**Pull request by redcreeper14385**
## Summary

This pull requests removes the confusing brackets system for the migrating guide and instead just puts everything into two sections - `Changes` and `Removals`. An `Additions` section will be added eventually detailing the new interactions support.

If a dev wants to find something specific within the guide, they can just use the sidebar to find it quickly.

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by ooliver1** [comment]
yea i mostly just copied from the dpy gist, im gonna download and check if this works first

**Comment by redcreeper14385** [comment]
> yea i mostly just copied from the dpy gist, im gonna download and check if this works first

If you tell me how to test it then I'll do it myself

**Comment by TAG-Epic** [comment]
Additions should not be added as this is not breaking changes.

**Comment by redcreeper14385** [comment]
> Additions should not be added as this is not breaking changes.

OK 👍

**Comment by ooliver1** [comment]
on windows powershell I cd into the docs dir then do ``.\make html``, then you find html in the _build/html dir
I dont know how I set this up actually

**Review by ooliver1 — APPROVED** [review]
all LGTM

**Review by TAG-Epic — APPROVED** [review]
LGTM

**Pull request merged**
