### PR TITLE
added spooktober discord banners

### PR DESCRIPTION
**Pull request by Glowstik-YT**
created discord banner in photoshop

idk what to put here ._.

### CODE REVIEW

**Review by DenverCoder1 — COMMENTED** [review]
Maybe remove the svg, doesn't look like it worked

image

**Comment by DenverCoder1** [comment]
Also text doesn't look like it's lined up properly and it's a different font from everything else

image

**Comment by Glowstik-YT** [comment]
> Also text doesn't look like it's lined up properly and it's a different font from everything else
> 
> image

Yea I fixed everything up now

**Review by TAG-Epic — APPROVED** [review]

**Review by DenverCoder1 — APPROVED** [review]

**Review by ooliver1 — APPROVED** [review]

**Review by DenverCoder1 — COMMENTED** [review]
Maybe rename to `nextcord-banner-halloween.png` to differentiate from server logo version?

**Review by TAG-Epic — CHANGES_REQUESTED** [review]
Maybe change the name to banner?

**Pull request merged**
