### PR TITLE
fix(client): add tag-epic to license header

### PR DESCRIPTION
**Pull request by MaskDuck**
## Summary

apply license 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Skelmis** [comment]
property apply?

**Comment by MaskDuck** [comment]
i mean... rightly apply

**Comment by MaskDuck** [comment]
*properly

**Comment by MaskDuck** [comment]
uh hello?

**Comment by Skelmis** [comment]
> uh hello?

What..? lmao

**Review by ooliver1 — APPROVED** [review]
idk what makes this so breaking tbh

**Pull request merged**
