### PR TITLE
feat: add message snapshots/forwarding

### LINKED ISSUE #1214: Message forwarding
### Summary

Allow bots to see forwarded messages 

### What is the feature request for?

The core library

### The Problem

Bots aren't unable to see forwarded messages, causing users to use this to bypass moderation bot filters.

### The Ideal Solution

See forwarded messages, possibly inside of a on_message event?

### The Current Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by spifory**
## Summary

- Implements discord/discord-api-docs#6833
- Closes #1214

Tested with: https://paste.nextcord.dev/?id=1728150917630869 & https://paste.nextcord.dev/?id=1729079833667392

image
image

## This is a **Code Change**

- [x] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

### CODE REVIEW

**Comment by spifory** [comment]
> Heyo, I'll try to look at the code further and test this myself later (in 6-8 hours hopefully), I assume you've actually tested this thoroughly @spifory?

Sorry, forgot to respond, yes I've tested this almost thorougly, haven't tried to break it, though

**Review by alentoghostflame — APPROVED** [review]
While I didn't do a super in-depth test, forwarding a message works as expected and this code looks good and isn't erroring. Approved.

**Comment by ItsSNOWMOBILE** [comment]
Tested it and it seems solid, didn't run into errors.
Approved.

**Comment by alentoghostflame** [comment]
Two approval reviews, even though the 2nd person didn't do an actual GitHub Certified Review™. Merging.

**Pull request merged**
