### PR TITLE
Update head_or_tails.py example with detailed comments

### PR DESCRIPTION
**Pull request by justanotherbyte**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by TAG-Epic — CHANGES_REQUESTED** [review]
This is just excessive documentation.

**Review by H4ckerxx44 — COMMENTED** [review]
Do you want to add comments for all the examples, too? 
Would fit in the examples good I think

**Comment by lucaytpols** [comment]
> Do you want to add comments for all the examples, too?
> Would fit in the examples good I think

Yeah I mean that is a good idea

**Comment by TAG-Epic** [comment]
This is just pointless comment spam imo.

**Pull request closed without merging**
