### PR TITLE
Adding 3.10 in supported python versions

### PR DESCRIPTION
**Pull request by VincentRPS**
## Summary

Adds Python 3.10 As A Supported Version Of Python

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TAG-Epic** [comment]
3.10 should be tested before it's supported

**Comment by VincentRPS** [comment]
> 3.10 should be tested before it's supported

I have tested it it’s my main python version and I’ve had no problems with it and nextcord

**Comment by veni-vidi-code** [comment]
have you also tested voice, every method and commands ext?

**Comment by VincentRPS** [comment]
> have you also tested voice, every method and commands ext?

I’ve tested it in most commands ext method but actually not voice yet

**Review by TAG-Epic — CHANGES_REQUESTED** [review]
This doesn't change it in the unaliased version

**Pull request merged**
