### PR TITLE
Fixed typos in docs

### PR DESCRIPTION
**Pull request by DenverCoder1**
## Summary

Fixed 50+ spelling and grammar mistakes in the readme and documentation.

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by jgayfer** [comment]
You've broken almost all of the links in `docs/api.rst`. The colons and such are there for a reason.

Aside from that, most of the changes here appear to be more of an opinion on how language should be structured rather than typos or mistakes.

**Review by TAG-Epic — APPROVED** [review]

**Comment by TAG-Epic** [comment]
@jgayfer sorry didn't see your message. Which links have been broken?

**Comment by jgayfer** [comment]
@TAG-Epic He removed every single colon from `docs/api.rst`

**Comment by DenverCoder1** [comment]
Sorry about that mistake. I don't know how I forgot to replace them. My new PR should fix this.

**Comment by ooliver1** [comment]
@DenverCoder1 quick tip with sphinx rst, double colons, double dots, appears to be weird underscores, backticks surrounding something prefixed with something like :meth: are all formatting of restructured text sphinx

**Comment by DenverCoder1** [comment]
Thanks, @ooliver1. I'm aware of the basic rst syntax. I removed the colons only temporarily to make it easier to spot the typos. I intended to make a copy without them and then put them back immediately but somehow for that file, either the undo didn't register or I forgot.

**Comment by ooliver1** [comment]
Oh right okay

**Pull request merged**
