### PR TITLE
Formatting per-commit ci/cd

### PR DESCRIPTION
**Pull request by RPSMain**
## Summary

Successor To #261 

Per-Commit Linting

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by ooliver1** [comment]
@RPSMain have you tried `darker`, it's black but per commit

**Comment by RPSMain** [comment]
@ooliver1 i don't know if this is failing or it's meant to do this https://github.com/nextcord/nextcord/runs/4416563517

**Comment by ooliver1** [comment]
It looks like it's successful to me

**Review by Skelmis — APPROVED** [review]

**Comment by Skelmis** [comment]
Looks good to me, although you may wish to change the name to be something a bit more descriptive. `format` is kinda ambiguous

**Comment by vcokltfre** [comment]
Format makes sense to me; in the context of a library of code, format is pretty unambiguous

**Review by ooliver1 — APPROVED** [review]
if this works then yeah this is good

**Pull request merged**
