### PR TITLE
refactor(embeds)!: make certain required parameters positional

### PR DESCRIPTION
**Pull request by toolifelesstocode**
## Summary

This pull request makes certain `Embed` attribute parameters positional.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by EmreTech** [comment]
The PR title should be changed to specify that these changes are for embeds and nothing else.

**Review by EmreTech — COMMENTED** [review]
I'm very confused on how these changes affect whether or not a parameter is required or not. All these changes do is make certain parameters from keyword only to keyword/positional.

**Comment by toolifelesstocode** [comment]
> I'm very confused on how these changes affect whether or not a parameter is required or not. All these changes do is make certain parameters from keyword only to keyword/positional.

Okay so, to end the confusion for everyone, I worded the title wrong. It is just making certain parameters positional, not that it makes them required, I had just worded it wrong, when really I was just trying to make them positional. My mistake, sorry 😅

**Review by EmreTech — CHANGES_REQUESTED** [review]
Unfortunately, the claim in your description doesn't support these changes at all. Making certain parameters positional/keyword doesn't make them required or not (as I've already gone over).

**Review by teaishealthy — APPROVED** [review]

**Review by Skelmis — APPROVED** [review]

**Review by DenverCoder1 — APPROVED** [review]
Not sure that it's necessary, but seems fine

**Review by ooliver1 — COMMENTED** [review]
Changing them to positional doesn't really change if they are required or not, `set_field_at(0, "title", "value")` doesn't look better than `set_field_at(0, name="title", value="value")`

+ this isn't breaking since it allows both forms of args

**Pull request closed without merging**
