### PR TITLE
Added Installing Seperate Ext's Into The ``setup.py``

### PR DESCRIPTION
**Pull request by VincentRPS**
## Summary

Made It So if You Do
``pip install nextcord[ipc]`` Or ``pip install nextcord[menus]`` it would install the separate python projects for those

## Checklist

- [x] This PR adds Something To Setup.py

### CODE REVIEW

**Review by Skelmis — APPROVED** [review]
lgtm

**Comment by ooliver1** [comment]
We have the events and alternatives? those packages don't exist

**Comment by VincentRPS** [comment]
> We have the events and alternatives? those packages don't exist

i am currently upkeeping them

**Comment by TAG-Epic** [comment]
This will not be merged as NC doesn't depend or softdepend on these.

**Pull request closed without merging**
