### PR TITLE
Merge: #298

### PR DESCRIPTION
**Pull request by Lulalaby**

### CODE REVIEW

**Review by VincentRPS — APPROVED** [review]

**Review by vcokltfre — APPROVED** [review]

**Review by ToasterUwU — APPROVED** [review]
With the get function fix, it doesn't have the potential to break and adds a valueable feature. So here is my approval.

**Review by TAG-Epic — CHANGES_REQUESTED** [review]
This should probably be a enum and then fallback to a string??

**Comment by Lulalaby** [comment]
No.
Better don't do this.

**Comment by Lulalaby** [comment]
Reason: https://docs.dcs.aitsys.dev/articles/application_commands/translations/reference.html#valid-locales

**Comment by vcokltfre** [comment]
I'm not sure how that link somehow proved that we shouldn't use an enum?

**Comment by Lulalaby** [comment]
We talked in the guild about it.
I won't do anything more.
If you want to switch it to an enum, please do it yourself.

**Review by DenverCoder1 — APPROVED** [review]
I think it's fine to leave it as a string

It's more easily maintainable this way and it matches the [docs' specifications](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure)

Imo, maintaining a list of locales would be unnecessary and overcomplicating it

**Review by TAG-Epic — APPROVED** [review]
Hmmm revised my thoughts on this. Why not!

**Comment by Lulalaby** [comment]
Finally :p

**Pull request merged**
