### PR TITLE
fix(Member): add tag-epic to license headers

### PR DESCRIPTION
**Pull request by MaskDuck**
## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by EmreTech** [comment]
Looks good, but why is this a breaking change?

**Comment by ooliver1** [comment]
thats a good point, @MaskDuck why do you mark all your PRs as breaking changes?

**Comment by koala9712** [comment]
aaaand the `This PR is a breaking change` option has not been checked in the description.
@MaskDuck , the `!` in the naming format signify a breaking change, they aren't there for decroation

**Comment by EmreTech** [comment]
> aaaand the `This PR is a breaking change` option has not been checked in the description.
> 
> @MaskDuck , the `!` in the naming format signify a breaking change, they aren't there for decroation

If it was an actual breaking change, then that would have to be checked. However, it's only like one line added to the copyright notice of a file. It's not a breaking change at all. In fact, it's not even a code change.

**Comment by EmreTech** [comment]
> aaaand the `This PR is a breaking change` option has not been checked in the description.
> 
> @MaskDuck , the `!` in the naming format signify a breaking change, they aren't there for decroation

If it was an actual breaking change, then that would have to be checked. However, it's only like one line added to the copyright notice of a file. It's not a breaking change at all. In fact, it's not even a code change.

**Comment by EmreTech** [comment]
> aaaand the `This PR is a breaking change` option has not been checked in the description.
> 
> @MaskDuck , the `!` in the naming format signify a breaking change, they aren't there for decroation

If it was an actual breaking change, then that would have to be checked. However, it's only like one line added to the copyright notice of a file. It's not a breaking change at all. In fact, it's not even a code change.

**Comment by koala9712** [comment]
@EmreTech That's what I meant...? I was explaining it for MaskDuck's benefit.

**Review by ooliver1 — APPROVED** [review]

**Review by koala9712 — APPROVED** [review]

**Pull request merged**
