### PR TITLE
Add svg banner and logo (higher quality)

### PR DESCRIPTION
**Pull request by DenverCoder1**
## Summary

Added a higher quality banner using SVG format and a vectorized version of the logo.

nextcord-banner

nextcord-logo

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TAG-Epic** [comment]
Would there be possible to have a PNG and a svg version?

**Comment by DenverCoder1** [comment]
> Would there be possible to have a PNG and a svg version?

Of the banner or logo?

**Comment by TAG-Epic** [comment]
Both

**Comment by DenverCoder1** [comment]
Theoretically, yes. You could always create a png from the svg.

**Comment by DenverCoder1** [comment]
I can add them now

**Pull request merged**
