### PR TITLE
localization examples

### PR DESCRIPTION
**Pull request by i80287**
Two examples for the localization: localization for the name and description of the slash command and for the SlashOption in  French, German and Spanish

### CODE REVIEW

**Comment by ooliver1** [comment]
May I ask why the PR template was deleted?

**Comment by i80287** [comment]
> May I ask why the PR template was deleted?

I am sorry, what is the PR template?

**Comment by ooliver1** [comment]
image
Pre-filled when you create a PR.

**Comment by i80287** [comment]
> image Pre-filled when you create a PR.

Im sorry, I have not ever pulled any requests, I thought I must write what I have changed

**Pull request closed without merging**
