### PR TITLE
Feat: Add user added reactions to the message reactions

### LINKED ISSUE #106: Adding reactions, but message.reactions is returning "[]"
### Link

https://github.com/Rapptz/discord.py/issues/1686

### PR DESCRIPTION
**Pull request by TAG-Epic**
## Summary
Add reactions to Message.reactions when message.add_reaction is called

Fixes #106 
## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by sairam4123 — APPROVED** [review]
LGTM

**Review by ooliver1 — COMMENTED** [review]
yea assuming this has been tested, LGTM

**Review by ooliver1 — APPROVED** [review]
~~forgot~~ forgor 💀  to approve

**Review by rf20008 — APPROVED** [review]
LGTM! it might be a little slow tho

**Comment by TAG-Epic** [comment]
Hmmm this code looks really bad now that I think about it. Gonna rewrite it later

**Comment by ooliver1** [comment]
did you rewrite it yet

**Comment by TAG-Epic** [comment]
Nope

**Pull request closed without merging**
