### PR TITLE
Linter

### LINKED ISSUE #260: Linting CI
### Summary

Linting CI

### What is the feature request for?

The core library

### The Problem

There's no linting process/ci

### The Ideal Solution

Use something like black with GH actions

### The Current Solution

Manually run a linter

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by RPSMain**
## Summary

Added Linting Workflow
Fixes #260

### CODE REVIEW

**Comment by ooliver1** [comment]
Btw "adds" is not a GitHub keyword to close issues on merge

**Comment by TAG-Epic** [comment]
This does not work for prs?

**Comment by Skelmis** [comment]
Given the discord discussions, this should likely not go through via ``black`` until the entire package is black'ed. Either transition to ``darker`` or maybe close?

**Comment by RPSMain** [comment]
@TAG-Epic would you be Okay with adding a pre-commit hook to nextcord?

**Pull request closed without merging**
