### PR TITLE
Add `Guild.online_members`

### PR DESCRIPTION
**Pull request by redcreeper14385**
## Summary

This pull request adds `online_members` to the `Guild` class.
This exists to save time for bot developers who need to quickly check if a user is online, or to find out how many users are online.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TAG-Epic** [comment]
Let's not add properties for everything.

**Comment by redcreeper14385** [comment]
I just thought they would be useful - it doesn't hurt to have them because it saves time for the developer.

**Comment by abrahammurciano** [comment]
`online_members` imo is definitely useful

**Comment by ooliver1** [comment]
Online members will be pretty useful for a few things, the extra properties make things more useful and cleaner

**Comment by TAG-Epic** [comment]
Considering all of these can be solved in one line I think it's really unnecessary.

**Comment by DenverCoder1** [comment]
Danny has usually been against implementing things that are not part of the Discord API.

If too many extra features are added it could add clutter and make it difficult to find the essential properties.

I do agree that it can be nice to have extra utils. It saves developers time so they don't have to write it themselves. Not sure if it needs to be part of the API Wrapper though.

**Comment by ooliver1** [comment]
Online members is kinda part of the mobile client but I don’t know if the permission thing really works

**Comment by TheMultii** [comment]
I don't really know if this needs to be part of the API wrapper. It might be a good idea to create some other library to add properties like `online_members` 🤔

**Comment by redcreeper14385** [comment]
> I don't really know if this needs to be part of the API wrapper. It might be a good idea to create some other library to add properties like `online_members` 🤔 

I wouldn't say a completely separate library, although perhaps an `ext` module so that users can choose. 

It could be called `ext.variables` or something similar.

**Comment by ooliver1** [comment]
surely it would have to be part of the Guild class though, its really just add it or dont add it

**Comment by ooliver1** [comment]
unless if you pass in a Guild object, thats just more effort than making the list comp yourself

**Comment by redcreeper14385** [comment]
Could you explain why you suddenly closed this?

**Comment by redcreeper14385** [comment]
Anything?

**Comment by abrahammurciano** [comment]
> Let's not add properties for everything.

Probably this is why

**Comment by redcreeper14385** [comment]
> > Let's not add properties for everything.
> 
> Probably this is why

Yes but we then agreed to let the community give their opinion first.

**Comment by AstroidDev** [comment]
Maybe add `nextcord.ext.utils` and then you could add `nextcord.ext.utils.getOnlineMembers(guild: discord.Guild)` along with other useful utils.

**Comment by ooliver1** [comment]
That's about as long as just

``[m for m in guild.members if member.status.online]``

**Comment by TAG-Epic** [comment]
This is unnecessary imo as it can be solved by a simple oneliner.

**Pull request closed without merging**
