### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by codeman1o1**
## Summary

This PR generally improves code style.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by codeman1o1** [comment]
> please fix docs?

Are you talking about the failing checks because I haven't changed the behavior of things?

**Comment by MaskDuck** [comment]
yes

**Comment by MaskDuck** [comment]
most things failed

**Comment by ooliver1** [comment]
> most things failed

this PR does not seem to cause the `MISSING` import error at a glance

**Comment by codeman1o1** [comment]
The same checks fail for other PR's aswell

**Comment by MaskDuck** [comment]
pretty sure 594 is having a different error, 594's one was `ForumChannel` cant be imported.

**Comment by ooliver1** [comment]
> pretty sure 594 is having a different error, 594's one was `ForumChannel` cant be imported. 596-598 didnt fail.

correct, because it actually doesnt exist

**Comment by MaskDuck** [comment]
@codeman1o1 ^

**Comment by codeman1o1** [comment]
Fixed it, I accidentally removed the `MISSING` import

**Comment by koala9712** [comment]
Alot of the changes are unnecessary and will change once #596 is merged

**Review by DenverCoder1 — COMMENTED** [review]
It would help if you could highlight the main code changes that could affect functionality.

It seems like everything was formatted with black, so it's very hard to find anything that could be important to review.

In the future, it might be a good idea to format with black as its own commit and make other changes in separate commits so that the black commit can be excluded when reviewing.

I have a few suggestions regarding improving code formatting.

**Comment by codeman1o1** [comment]
Yeah, those changes were automatically made by `black` or the `prettier` extension.
I am going to do a few things:
1. Undo **all** changes
2. Set PR to `draft`
3. Turn off `black`
4. Turn off `prettier`
5. Refactor with `flake8` and `sonarlint`
6. Commit
7. Turn on `black`
8. Set `black` line length to `100`
9. Save (to run `black`)
10. Commit
11. Turn on `prettier`
12. Save (to run `prettier`)
13. Commit
14. Turn off `draft` for PR

**Comment by codeman1o1** [comment]
Never mind. I will delete the branch and follow the steps above and make another PR

**Pull request closed without merging**
