### PR TITLE
[BREAKING] fix(contributing-guideline): removing dapi.

### PR DESCRIPTION
**Pull request by MaskDuck**
## Summary

yk, it is weird to ask about nextcord in that channel, especially the owner of dpy really hates nextcord.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Skelmis** [comment]
I'm confused, how are all of your docs changes pr's "[BREAKING]" when they change no code nor break any established syntax. It breaks nothing for the end users in any way.

**Comment by vcokltfre** [comment]
Furthermore, why is this PR
- Not marked as a documentation change
- Appearing to intentionally annoy the discord.py community by saying Danny "really hates nextcord"

**Comment by MaskDuck** [comment]
i didnt intend to annoy dpy community.

**Comment by MaskDuck** [comment]
but if oyu dont want to, yeah.

**Pull request closed without merging**
