### PR TITLE
feat(guild): update `Guild.stickers_limit` to match the default limit of 5

### PR DESCRIPTION
**Pull request by MaskDuck**
## Summary

title, cant guarantee on the lintings through

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues. 
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by ooliver1** [comment]
can you provide a reference to where the info on 5 sticker slots is from? your summary doesnt seem to explain anything

**Comment by DenverCoder1** [comment]
@ooliver1 There's a popup that appears on some servers

image

I'm not sure if it's rolled out to all servers yet, or just some though.

**Comment by H4ckerxx44** [comment]
Can confirm, 5 free stickers for me aswell. Not a community guild I might add.

grafik

**Comment by MaskDuck** [comment]
@ooliver1 https://discord.com/channels/613425648685547541/697489244649816084/984667965888806993

**Review by ooliver1 — APPROVED** [review]

**Review by DenverCoder1 — APPROVED** [review]

**Pull request merged**
