### PR TITLE
Deleting the discord directory due to importerrors

### PR DESCRIPTION
**Pull request by rf20008**
## Summary

ImportErrors happen when trying to import both nextcord and discord.py, so removing the discord directory should fix that. Also most of the functionality is in the nextcord directory

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TAG-Epic** [comment]
The import errors was fixed in #52. The reason the discord folder exists is because old code or external libraries should use nextcord.

**Comment by rf20008** [comment]
that makes sense
:)

**Comment by redcreeper14385** [comment]
Does #70 fix this at all?

**Comment by redcreeper14385** [comment]
I'd rather not remove the folder for compatibility reasons.

**Comment by redcreeper14385** [comment]
Oh I'm blind - didn't realise it was closed.

**Pull request closed without merging**
