### PR TITLE
adds with_counts in fetch_guild

### PR DESCRIPTION
**Pull request by JDJGInc**
formatted with darker . :)
as maskduck told me was needed, also properly linted

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by TAG-Epic — APPROVED** [review]
Not tested, docs looks fine

**Comment by JDJGInc** [comment]
image
I have tested this, Output:
client is ready
506 281
None None

```python
import nextcord
from nextcord.ext import commands

bot = commands.Bot(command_prefix = "n/",intents = nextcord.Intents.all())

@bot.listen()
async def on_ready():
    print("client is ready")

@bot.command()
async def test(ctx):
    
    guild = await bot.fetch_guild(ctx.guild.id)
    print(guild.approximate_member_count, guild.approximate_presence_count)

    guild = await bot.fetch_guild(ctx.guild.id, with_counts = False)
    print(guild.approximate_member_count, guild.approximate_presence_count)

    await ctx.send("Alright Check the Console")

bot.run("TOKEN")
```

**Review by MaskDuck — APPROVED** [review]
looks good

**Review by DenverCoder1 — APPROVED** [review]

**Review by Skelmis — APPROVED** [review]

**Review by ooliver1 — APPROVED** [review]
tested :)

**Pull request merged**
