### PR TITLE
chore: update api version to v10

### PR DESCRIPTION
**Pull request by koala9712**
Updates to API version 10

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I think these should be changed as well

https://github.com/koala9712/nextcord/blob/acebca6e1d27232adf55bb3f6932c6c861cea07c/nextcord/http.py#L1909

```py
        if zlib:
            value = '{0}?encoding={1}&v=9&compress=zlib-stream'
        else:
            value = '{0}?encoding={1}&v=9'
```

https://discord.com/developers/docs/topics/gateway#connecting-gateway-url-query-string-params

**Comment by DenverCoder1** [comment]
I believe this change should make Messagr.content optional among possibly other things

v10 Discussion - https://github.com/discord/discord-api-docs/discussions/4510

**Comment by koala9712** [comment]
>

**Comment by koala9712** [comment]
Oops, I think it can be done in a future PR with the other things, as it is not necessary as of now.
This one can bump the version to v10 only.

**Comment by ooliver1** [comment]
why bump the version if the code can’t handle the change

or am I misunderstanding your message

what you said is "bump version then support it later"

**Comment by DenverCoder1** [comment]
This can't be merged into master before the changes are addressed.

For example, I am noticing this crashes if Message intent is disabled in the developer portal.

If you'd rather not finish the migration, we could possibly have this PR and others target a side branch until v10 is ready to be merged into master.

**Comment by veni-vidi-code** [comment]
We have a new branch for apiv10 (https://github.com/nextcord/nextcord/tree/community/apiv10) please consider pulling to that for now, so we can start implemting all necessary changes

**Comment by koala9712** [comment]
#464 furthers, this can be closed then

**Pull request closed without merging**
