### PR TITLE
Update application_commands/cog_example to ClientCog

### PR DESCRIPTION
**Pull request by ToasterUwU**
## Summary

This updates the example for application command Cogs to the actual ClientCog. 
It also shows basic usage of the cog_check equivalent for ClientCog.

## Checklist

- [X] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by MaskDuck** [comment]
what is the point of this?

**Comment by koala9712** [comment]
It may deserve a separate file for itself, `cog_checks` or something similar.
the setup function was removed, huh?

Has this been tested?

**Comment by ToasterUwU** [comment]
> what is the point of this?

Keeping examples updated helps people to understand better. Examples are of no use when outdated.

**Comment by ToasterUwU** [comment]
> It may deserve a separate file for itself, `cog_checks` or something similar.
> the setup function was removed, huh?
> 
> Has this been tested?

1. I don't think so. The old version was plain outdated, using the wrong class and everything and I don't see a reason why a feature of the ClientCog should be separate from the rest. 

2. Yes. I checked the box that I did. Took the thing, changed the example IDs to actual IDs and added the cog and run the Client. Worked like intended.

**Comment by MaskDuck** [comment]
> > what is the point of this?
> 
> Keeping examples updated helps people to understand better. Examples are of no use when outdated.

i havent heard of that breaking change. the old one still works and imo it is better to use `commands.Cog` instead of `ClientCog`. if there is any breaking change the author of the pr which made breaking change should also replace the old example with the new example as well.

**Comment by ToasterUwU** [comment]
> > > what is the point of this?
> > 
> > Keeping examples updated helps people to understand better. Examples are of no use when outdated.
> 
> i havent heard of that breaking change. the old one still works and imo it is better to use `commands.Cog` instead of `ClientCog`. if there is any breaking change the author of the pr which made breaking change should also replace the old example with the new example as well.
> 

There was no breaking change. But normal Cogs are just simply not intended to be used for application commands, the ClientCog is.

The ClientCog was made for the application commands, the ext.commands.Cog was made for the old system.
Using a class made for something is always better when using something which is not intended for that (anymore).

Besides that: There are features that ClientCog brings like the cog-wide check, which are not possible with the old Cog. cog_check only works for the commands.command(s).

Positive: Using proper class for application commands (the topic of that example), having the check, having the pre and after invoke functions.
Negative: Nothing

**Comment by DenverCoder1** [comment]
commands.Cog inherits from ClientCog, so anything that can be done with ClientCog should also be possible with commands.Cog.

ClientCog is just a stripped down version of Cogs that you can use if you really don't want to use the commands extension.

Besides "prefix commands", the commands extension does have some additional features that ClientCog doesn't have, such as listeners.

For simplicity, we've been mainly sticking to using ext.commands in examples to not confuse users with having multiple versions of everything. (Eg. You *can* use nextcord.Client instead of commands.Bot, but Client is essentially just a more stripped down version of Bot)

@alentoghostflame Do you have an opinion on this?

**Comment by ToasterUwU** [comment]
In my opinion the stuff from the nextcord.ext namespace should only be used if necessary. Since it's the old/other way of doing stuff, I'm also not a fan of mixing the two systems just because people got used to it.

The example things should be a minimal example of what to do, and since this is the example for the new/builtin command system, I give the minimal example for the ClientCog. No mixing systems, cleaner example.

**Comment by MaskDuck** [comment]
@ToasterUwU can you post the code you tried? since `bot.load_extension` does run setup and it is only available in `commands.Bot`

**Comment by ToasterUwU** [comment]
> @ToasterUwU can you post the code you tried? since `bot.load_extension` does run setup func/coro and it is only available in `commands.Bot`

@MaskDuck 

That's not the way to use it. That would be mixing old and new systems.

Use the Client instead of Bot. Client.add_cog()

**Comment by MaskDuck** [comment]
...

what if i need to init some more shit in the `__init__` function?

**Comment by MaskDuck** [comment]
@ToasterUwU

**Comment by ooliver1** [comment]
`add_cog(Class(bot/client))` calls the `__init__` as thats how classes works

**Comment by MaskDuck** [comment]
ic.

i still want to init some async stuff so i usually do that in the setup func, but fine

**Comment by ooliver1** [comment]
ive made a discussion #588 so to not clutter this page (so it can be used for reviews)

**Comment by ToasterUwU** [comment]
> ...
> 
> what if i need to init some more shit in the `__init__` function of the cog?

@MaskDuck Than just do it. The add_cog wants a initialized object, not the class. So do all the stuff you need and than add it. `client.add_cog(CogName(arg1=69, arg2=420))`

**Comment by ToasterUwU** [comment]
I think I should close this, since it's unneeded. 

Whenever the Cog class is moved, this example, most likely, will be wrong anyways.

**Pull request closed without merging**
