### PR TITLE
Add Build Test

### PR DESCRIPTION
**Pull request by RPSMain**
## Summary

Adding A Test Which Builds Nextcord

## Checklist

- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by TAG-Epic — CHANGES_REQUESTED** [review]
We don't use build to build nextcord? Also is this needed?

**Comment by ooliver1** [comment]
Nc isn't a built library

**Comment by RPSMain** [comment]
> We don't use build to build nextcord? Also is this needed?

It is great for pointing out errors before pypi uploads and stuff, and if you want I could change it to sdist even if there is no difference

**Comment by Skelmis** [comment]
What "errors"

You can build distributable with invalid code fine..?

**Comment by TAG-Epic** [comment]
Yeah... Even if this would be merged I would prefer using no deps aaand testing unaliased too.

**Comment by ooliver1** [comment]
python is an interpreted language mostly (cpthon), so unlike compiled languages, it's harder to point out errors

as it's dynamically typed, it's hard to pick out every error

**Pull request closed without merging**
